feat: add ability to include external templates

diff --git a/lib/templates/deployment.yml b/lib/templates/deployment.yml
--- a/lib/templates/deployment.yml
+++ b/lib/templates/deployment.yml
@@ -93,19 +93,23 @@ documents:
             - <<: *app_container
               name: *job_app_name
               command: "/bin/bash -c <%= deployment.job_command %>"
-              ports: []
 
+            <% if deployment.job_sidekiq_alive_gem %>
+              <%= include_template "_sidekiq_alive_gem.yml.erb" %>
+            <% else %>
+              ports: [ ]
               <% if (deployment.job_services || []).any? %>
               livenessProbe: &liveness_probe
                 exec:
                   command: [ /bin/sh, -c,
-                    'if [ $(ps -ef | grep "<%= deployment.job_services.join("\|") %>" | grep -v "grep" | wc -l) -lt <%= deployment.job_services.count %> ]; then
-                      echo "Some required services are not running"; exit 1;
-                    fi' ]
+                      'if [ $(ps -ef | grep "<%= deployment.job_services.join("\|") %>" | grep -v "grep" | wc -l) -lt <%= deployment.job_services.count %> ]; then
+                           echo "Some required services are not running"; exit 1;
+                       fi' ]
                 initialDelaySeconds: 120
                 periodSeconds: 30
               readinessProbe: *liveness_probe
               <% end %>
+            <% end %>
 
             - *cloudsql_container
             - <<: *logs_container
